title: Julie Shapiro
description: System's Software Engineer
author: "Julie Shapiro"

#theme: jekyll-theme-cayman
theme: "minima"

github_username: "julie-is-late"
bsky_username: "@weeb.site"

show_excerpts: true

header_pages:
  - _pages/frontpage.md
  - _pages/resume.md
  - _pages/blog.md
  - _pages/photography.md

include:
  - _pages

#google_analytics:

minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/julie-is-late" }
    - { platform: bluesky, user_url: "https://bsky.app/profile/weeb.site" }
