title: "Julie Shapiro"
description: "System's Software Engineer"
author: "Julie Shapiro"

theme: "minima"

github_username: "julie-is-late"
bsky_username: "@weeb.site"

show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

header_pages:
  - _pages/frontpage.md
  - _pages/resume.md
  - _pages/blog.md
  - _pages/photography.md

include:
  - _pages

#google_analytics:

minima:
  # skin: solarized  ### only supported in 3.0, gh pages is 2.5.1
  social_links:
    - { platform: github,  user_url: "https://github.com/julie-is-late" }
    - { platform: bluesky, user_url: "https://bsky.app/profile/weeb.site" }

exclude:
    - .gitignore
    - LICENSE
    - README.md
