title: "Julie Shapiro"
description: "System's Software Engineer Specializing in Compilers and Machine Learning"

author:
  name: "Julie Shapiro"
  email: "julie@weeb.site"

# theme: "minima"
remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-remote-theme

github_username: "julie-is-late"
bsky_username: "@weeb.site"

show_excerpts: true

header_pages:
  - _pages/frontpage.md
  - _pages/resume.md
  - _pages/blog.md
  - _pages/photography.md

include:
  - _pages

minima:
  skin: auto
  date_format: "%Y-%m-%d"
  # skin: solarized  ### only supported in 3.0, gh pages is 2.5.1
  social_links:
    - { platform: github,  user_url: "https://github.com/julie-is-late" }
    - { platform: bluesky, user_url: "https://bsky.app/profile/weeb.site" }

exclude:
    - .gitignore
    - LICENSE
    - README.md

footer:
  custom_text: "© 2024 Julie Shapiro. All rights reserved."
